Add Xcake and Tuist as alternatives
Lightricks/Kintsugi pull request #15
Opened 2021-07-08 16:01 UTC by natanrolnik

2021-07-14 08:12 UTC, byohay requested changes
@natanrolnik, thanks for the PR!
Some small comments.

2021-07-14 08:12 UTC, byohay commented on README.md
> +All of the alternatives below allow you to generate your Xcode projects based on a spec or manifest. You commit these files to git, and can even remove the `.xcodeproj` files from git. If you decide
I'd remove the last sentence, I prefer to have a general description as the readme's real estate is expensive.

2021-11-30 13:26 UTC, byohay commented
@natanrolnik please fix the comments or I'll close the PR :)

2021-11-30 13:54 UTC, natanrolnik commented
@byohay done, sorry for dropping the ball on this.

2021-12-15 08:32 UTC, byohay approved these changes

2021-12-15 08:41 UTC, merged