Kintsugi: Add release workflow.
Lightricks/Kintsugi pull request #61
Opened 2022-05-01 11:49 UTC by byohay

2022-05-01 13:50 UTC, ashdnazg requested changes

2022-05-01 13:50 UTC, ashdnazg commented on .github/workflows/release.yml
> +    runs-on: macos-10.15
I think this can also run on `ubuntu-latest`

2022-05-02 07:15 UTC, byohay commented
@ashdnazg done

2022-05-02 07:23 UTC, ashdnazg approved these changes

2022-05-02 07:23 UTC, merged