apply_change_to_project: Handle remove configuration list change.
Lightricks/Kintsugi pull request #82
Opened 2022-08-09 12:40 UTC by byohay

Also, refactor applying added changes for symmetry with removed changes.

2022-08-10 13:27 UTC, ashdnazg requested changes
F&S

2022-08-10 13:27 UTC, ashdnazg commented on lib/kintsugi/apply_change_to_project.rb
> +            child_component_of_object_list(component, removed_change, removed_change["displayName"])
this function expects component to be non-nil

2022-08-10 13:27 UTC, ashdnazg commented on lib/kintsugi/apply_change_to_project.rb
> +        add_child_to_component(parent_component, change[:added], change_path)
same

2022-08-11 06:10 UTC, byohay commented
@ashdnazg I added guards around places that need `component`. I also added this dependency in change[:added], as it always needs the parent component.

2022-08-15 10:14 UTC, ashdnazg approved these changes
I think it's ok,
Note that in the commit message you still mention symmetry, but that's no longer the case.
Also we need to remember to fail `added` if it will override a different existing value. Probably in a different PR.

2022-08-15 13:59 UTC, merged