apply_change_to_project: fix group moves.
Lightricks/Kintsugi pull request #88
Opened 2022-09-01 15:35 UTC by ashdnazg

2022-09-08 08:15 UTC, byohay requested changes
round.

2022-09-12 08:30 UTC, ashdnazg commented on lib/kintsugi/apply_change_to_project.rb
> +      removals.reverse.each do |change, path|
fixed as discussed by sorting

2022-09-12 08:31 UTC, ashdnazg commented
F&Sed

2022-09-12 11:30 UTC, byohay approved these changes

2022-09-12 11:39 UTC, merged